// Code generated by scripts/generate-sdk-metadata.ts. DO NOT EDIT.

package pogodata

type DatasetDefinition struct {
	Path string
	Property string
}

var DatasetDefinitions = []DatasetDefinition{
	{Property: "costumes", Path: "costumes"},
	{Property: "forms", Path: "forms"},
	{Property: "invasions", Path: "invasions"},
	{Property: "items", Path: "items"},
	{Property: "locationCards", Path: "location-cards"},
	{Property: "moves", Path: "moves"},
	{Property: "pokemon", Path: "pokemon"},
	{Property: "questConditions", Path: "quest-conditions"},
	{Property: "questRewardTypes", Path: "quest-reward-types"},
	{Property: "questTypes", Path: "quest-types"},
	{Property: "raids", Path: "raids"},
	{Property: "routeTypes", Path: "route-types"},
	{Property: "teams", Path: "teams"},
	{Property: "types", Path: "types"},
	{Property: "weather", Path: "weather"},
}

var TranslationLocales = []string{
	"de",
	"en",
	"es",
	"es-mx",
	"fr",
	"hi",
	"id",
	"it",
	"ja",
	"ko",
	"pt-br",
	"ru",
	"th",
	"tr",
	"zh-tw",
}

var TranslationCategories = []string{
	"bonuses",
	"character-categories",
	"costumes",
	"descriptions",
	"evolution-quests",
	"forms",
	"grunt-quotes",
	"grunts",
	"items",
	"lures",
	"misc",
	"moves",
	"pokemon",
	"pokemon-categories",
	"quest-conditions",
	"quest-reward-types",
	"quest-titles",
	"quest-types",
	"types",
	"weather",
}
