import { mkdir, readdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

interface DatasetDefinition {
	path: string;
	property: string;
}

const V1_DIRECTORY = new URL("../data/v1/", import.meta.url);
const TRANSLATIONS_DIRECTORY = new URL(
	"../data/v1/translations/",
	import.meta.url,
);
const TYPESCRIPT_OUTPUT_FILE = new URL(
	"../packages/typescript/src/generated/metadata.ts",
	import.meta.url,
);
const GO_OUTPUT_FILE = new URL("../packages/go/metadata.go", import.meta.url);

function compareStrings(left: string, right: string): number {
	return left.localeCompare(right, "en");
}

async function listJsonBasenames(directory: URL): Promise<string[]> {
	const entries = await readdir(directory, { withFileTypes: true });

	return entries
		.filter((entry) => entry.isFile() && entry.name.endsWith(".json"))
		.map((entry) => entry.name.slice(0, -".json".length))
		.sort(compareStrings);
}

async function listTranslationCategories(
	locales: readonly string[],
): Promise<string[]> {
	const categories = new Set<string>();

	for (const locale of locales) {
		const localeDirectory = new URL(`${locale}/`, TRANSLATIONS_DIRECTORY);
		const localeCategories = await listJsonBasenames(localeDirectory);

		for (const category of localeCategories) {
			categories.add(category);
		}
	}

	return Array.from(categories).sort(compareStrings);
}

function toCamelCase(value: string): string {
	return value.replace(/-([a-z0-9])/g, (_, character: string) =>
		character.toUpperCase(),
	);
}

function formatTypescriptStringArray(
	name: string,
	values: readonly string[],
): string {
	const formattedValues = values
		.map((value) => `\t${JSON.stringify(value)},`)
		.join("\n");

	return `export const ${name} = [\n${formattedValues}\n] as const;\n`;
}

function formatTypescriptDatasetDefinitions(
	definitions: readonly DatasetDefinition[],
): string {
	const formattedDefinitions = definitions
		.map(
			(definition) =>
				`\t{ property: ${JSON.stringify(definition.property)}, path: ${JSON.stringify(definition.path)} },`,
		)
		.join("\n");

	return `export interface GeneratedDatasetDefinition {\n\treadonly path: string;\n\treadonly property: string;\n}\n\nexport const datasetDefinitions = [\n${formattedDefinitions}\n] as const satisfies readonly GeneratedDatasetDefinition[];\n`;
}

function formatGoStringArray(name: string, values: readonly string[]): string {
	const formattedValues = values
		.map((value) => `\t${JSON.stringify(value)},`)
		.join("\n");

	return `var ${name} = []string{\n${formattedValues}\n}\n`;
}

function formatGoDatasetDefinitions(
	definitions: readonly DatasetDefinition[],
): string {
	const formattedDefinitions = definitions
		.map(
			(definition) =>
				`\t{Property: ${JSON.stringify(definition.property)}, Path: ${JSON.stringify(definition.path)}},`,
		)
		.join("\n");

	return `type DatasetDefinition struct {\n\tPath string\n\tProperty string\n}\n\nvar DatasetDefinitions = []DatasetDefinition{\n${formattedDefinitions}\n}\n`;
}

async function main(): Promise<void> {
	const datasetSlugs = (await listJsonBasenames(V1_DIRECTORY)).filter(
		(datasetSlug) => datasetSlug !== "translations",
	);
	const datasetDefinitions: DatasetDefinition[] = datasetSlugs.map(
		(datasetSlug) => ({
			path: datasetSlug,
			property: toCamelCase(datasetSlug),
		}),
	);
	const translationLocales = await listJsonBasenames(TRANSLATIONS_DIRECTORY);
	const translationCategories =
		await listTranslationCategories(translationLocales);
	const typescriptContents = `// This file is generated by scripts/generate-sdk-metadata.ts.\n// Do not edit it manually.\n\n${formatTypescriptDatasetDefinitions(datasetDefinitions)}\n${formatTypescriptStringArray("translationLocales", translationLocales)}\n${formatTypescriptStringArray("translationCategories", translationCategories)}`;
	const goContents = `// Code generated by scripts/generate-sdk-metadata.ts. DO NOT EDIT.\n\npackage pogodata\n\n${formatGoDatasetDefinitions(datasetDefinitions)}\n${formatGoStringArray("TranslationLocales", translationLocales)}\n${formatGoStringArray("TranslationCategories", translationCategories)}`;

	await mkdir(dirname(TYPESCRIPT_OUTPUT_FILE.pathname), { recursive: true });
	await mkdir(dirname(GO_OUTPUT_FILE.pathname), { recursive: true });
	await writeFile(TYPESCRIPT_OUTPUT_FILE, typescriptContents);
	await writeFile(GO_OUTPUT_FILE, goContents);
}

await main();
