// This file is generated by scripts/generate-sdk-metadata.ts.
// Do not edit it manually.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DatasetDefinition {
	pub path: &'static str,
	pub property: &'static str,
}

pub static DATASET_DEFINITIONS: &[DatasetDefinition] = &[
	DatasetDefinition { property: "costumes", path: "costumes" },
	DatasetDefinition { property: "forms", path: "forms" },
	DatasetDefinition { property: "invasions", path: "invasions" },
	DatasetDefinition { property: "items", path: "items" },
	DatasetDefinition { property: "locationCards", path: "location-cards" },
	DatasetDefinition { property: "moves", path: "moves" },
	DatasetDefinition { property: "pokemon", path: "pokemon" },
	DatasetDefinition { property: "questConditions", path: "quest-conditions" },
	DatasetDefinition { property: "questRewardTypes", path: "quest-reward-types" },
	DatasetDefinition { property: "questTypes", path: "quest-types" },
	DatasetDefinition { property: "raids", path: "raids" },
	DatasetDefinition { property: "routeTypes", path: "route-types" },
	DatasetDefinition { property: "teams", path: "teams" },
	DatasetDefinition { property: "types", path: "types" },
	DatasetDefinition { property: "weather", path: "weather" },
];

pub static TRANSLATION_LOCALES: &[&str] = &[
	"de",
	"en",
	"es",
	"es-mx",
	"fr",
	"hi",
	"id",
	"it",
	"ja",
	"ko",
	"pt-br",
	"ru",
	"th",
	"tr",
	"zh-tw",
];

pub static TRANSLATION_CATEGORIES: &[&str] = &[
	"bonuses",
	"character-categories",
	"costumes",
	"descriptions",
	"evolution-quests",
	"forms",
	"grunt-quotes",
	"grunts",
	"items",
	"lures",
	"misc",
	"moves",
	"pokemon",
	"pokemon-categories",
	"quest-conditions",
	"quest-reward-types",
	"quest-titles",
	"quest-types",
	"types",
	"weather",
];
